# Generated by Django 3.1 on 2020-09-07 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200907_0834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messege_chat',
            old_name='username',
            new_name='test',
        ),
    ]
