# Generated by Django 3.1 on 2020-09-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200907_0840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messege_chat',
            old_name='test',
            new_name='_test',
        ),
        migrations.AlterField(
            model_name='messege_chat',
            name='_test',
            field=models.CharField(db_column='test', max_length=100),
        ),
    ]
