# Generated by Django 3.1 on 2020-09-07 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200907_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messege_chat',
            name='_test',
        ),
    ]
